import type { Metadata } from "next"
import { Sora, Outfit } from "next/font/google"
import "./globals.css"
import { SiteHeader } from "@/components/SiteHeader"

const sora = Sora({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-sora",
})

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-outfit",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${sora.variable} ${outfit.variable}`}>
      <body className="relative">
        <SiteHeader />
        {children}
      </body>
    </html>
  )
}
